name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.3
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install and run gunicorn
      run: |
        pip install gunicorn
        gunicorn --bind 0.0.0.0:5000 app:app

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
